[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[context.staging.environment]
  VUE_APP_HELLO_SIGN_API_KEY="502edd50a401b15f8f548ddcea56a77d"
  VUE_APP_UPLOADER_IMAGE_PRESET="browtricks_tenant_cms_images_dev"
  VUE_APP_UPLOADER_VIDEO_PRESET="browtricks_tenant_cms_videos_dev"

[context.master.environment]
  VUE_APP_HELLO_SIGN_API_KEY="28cc77a1d6ff153aef0b648184964873"
  VUE_APP_UPLOADER_IMAGE_PRESET="browtricks_tenant_cms_images"
  VUE_APP_UPLOADER_VIDEO_PRESET="browtricks_tenant_cms_videos"

